feat(button): created button with the Link to coupons
202306-NEA-DZ-FEW/team-five pull request #23
Opened 2023-10-16 20:51 UTC by melissasidisid

Created a button component along with the test

2023-10-16 21:11 UTC, Zino0031 commented on src/pages/index.jsx
The update to the index.jsx file is important for this feature but not for now. However, I'd like to reiterate that no changes should be made to the index.js file to prevent conflicts with other contributors and to maintain existing functionality.

2023-10-16 21:11 UTC, Zino0031 commented on src/pages/index.jsx
> +import Button from "@/components/Button/Button";
Remove this line

2023-10-16 21:11 UTC, Zino0031 commented on src/pages/index.jsx
> +            <Button />
Also remove this one

2023-10-16 21:13 UTC, Zino0031 requested changes
The changes in this pull request introduce a new button component and make some updates to the homepage component. Overall, it's a valuable addition. However, I want to stress that no changes should be made to the index.js file. This is to prevent conflicts with other contributors and to maintain existing functionality.

2023-10-17 14:55 UTC, DigitalDeveloperAM commented on src/components/Button/Button.jsx
> +            <button class='py-2 px-4 bg-green-500 text-white font-semibold shadow-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-400 focus:ring-opacity-75 rounded-full'>
Change the button color (#8CC540)

2023-10-17 15:07 UTC, DigitalDeveloperAM requested changes
I hope you're doing well. I've had a chance to review the recent changes you made to the color button in our project. Overall, it's looking great, but there are a few adjustments that need to be made to button color that match our  Figma design.

** The color of the button need to match this #8CC540 .

Keep up the Great work, and I appreciate your hard work and dedication to the project.

2023-10-20 09:25 UTC, melissasidisid commented
Hello, I removed the problem with the index.js and also added the submission form for the blog and events. I added the translation and the library that allow us to send an email to the client once he subscribes, and we receive an email too. With the information entered inside the form, the client will receive the information he entered too, and he will also receive a welcome message. While subscribing, the client will have a captcha. Now I will add the firebase and fix what there is to fix.

2023-10-20 18:01 UTC, Zino0031 approved these changes
Review:

I'm really impressed with the way you've handled this pull request. You've not only addressed all the changes and feedback but also went above and beyond by adding a  translation, and email functionality. Your dedication to improving our project is commendable. I approve this. 👍🚀

2023-10-20 18:02 UTC, mohamed70601 approved these changes
All previous issues ironed out, good job!

2023-10-20 19:17 UTC, DigitalDeveloperAM approved these changes
Excellent work @melissasidisid .

The button is perfect and all language file are looking good.

This PR is good to go. Well done!

2023-10-20 19:25 UTC, merged