2 create navbar component
202306-NEA-DZ-FEW/team-five pull request #28
Opened 2023-10-18 22:54 UTC by DigitalDeveloperAM

- Added the Navbar style and functionality for both language AR and EN.
- Added Logo according to figma design.
- Added Navigation Links to the Target pages.

![01](https://github.com/202306-NEA-DZ-FEW/team-five/assets/107757609/97feeba4-74fb-4fc0-a5fe-03397a033c5e)

![02](https://github.com/202306-NEA-DZ-FEW/team-five/assets/107757609/1e0971c9-5e7a-4fd8-8884-6d14cecf0260)

- Added Test files according the project requirement and file Structure.
- All test running correctly.

2023-10-18 23:44 UTC, Zino0031 requested changes
Hi Achref,

Great work on this pull request! However, I noticed that you've made some edits to index.js which we explicitly discussed not doing in order to avoid potential conflicts. Could you please remove the lines that you added to index.js and resubmit the changes?

Additionally, I'd like to remind you to request a review from us next time to notify us of your changes. This way, we can ensure that we're aware of and can provide feedback on the modifications made.

Thanks, and please let me know if you have any questions or need further clarification on the changes.

2023-10-18 23:44 UTC, Zino0031 commented on src/pages/index.jsx
> +import Navbar from "@/components/Navbar";
Can you remove this line

2023-10-18 23:44 UTC, Zino0031 commented on src/pages/index.jsx
> +
remove this line

2023-10-18 23:44 UTC, Zino0031 commented on src/pages/index.jsx
> +            <Navbar />
also remove this line

2023-10-19 14:05 UTC, melissasidisid commented
great job my friend keep up the good working

2023-10-19 14:08 UTC, melissasidisid approved these changes
good work keep it up

2023-10-19 14:13 UTC, HamidAhmidat approved these changes
great job achraf, Im excited to see the navbar . well done.

2023-10-19 14:21 UTC, merged